Maths single answer automarker
the-answerbook-project/custom-automarkers-template pull request #1
Opened 2024-07-15 14:23 UTC by matalex412

- This PR provides an example of automarking maths single answer type questions.
- We use SymPy to parse the latex of a student's answer into a math expression and compare semantic equality with a model answer
- We can also check that an answer does not contain specific mathematical features (e.g. an integral). This is to prevent students from entering the question as their answer)

2024-07-16 13:27 UTC, procaconsul requested changes

2024-07-16 13:27 UTC, procaconsul commented on examples/maths-automarker.py
Bearing in mind that a section can be made up by multiple tasks, and that you could have several such one-line math tasks per section, which avenue do you want to follow?

(1) Assume sections with one task, and mark the task 0 or max-mark accordingly
(2) Assume sections with many tasks, in which case you need a notion of the amount of marks each task contributes to the max mark (similarly to what appens with multiple choice)

Both of these are fine, (1) potentially simpler. Depending on the choice, we can make small adjustments to the script :)

2024-07-16 15:57 UTC, matalex412 commented on examples/maths-automarker.py
We have implemented approach (2) in commit a385dec

2024-07-16 16:09 UTC, procaconsul requested changes

2024-07-16 16:09 UTC, procaconsul commented on examples/maths-automarker.py
> +#         type: maths single answer
```suggestion
#       - instructions: |
#           Enter the integral.
#         type: processed handwriting
#       - instructions: |
#           Enter the derivative.
#         type: processed handwriting
```

2024-07-16 16:09 UTC, procaconsul commented on examples/maths-automarker.py
> +                            feedback = "Solution should not contain an integral"
If one of the tasks has Integral in the expression, feedback is set to "Solution should not contain an integral". However, it looks like that gets overwritten on the following loop cycle (i.e. on the next task) with "Awarded designated marks for answer". When do you want to use one feedback? When do you intend to use the other? Could it be simpler, for the demonstrative purpose of this script, to stick to the generic "Awarded designated marks for answer" directly on line 94? Obviously, more sophisticated alternatives are possible. I am just reasoning on what's easier to ship in a clean shape

2024-07-17 11:00 UTC, matalex412 commented on examples/maths-automarker.py
> +#         type: maths single answer
Addressed in f51a0cd

2024-07-18 12:37 UTC, merged